0903 test golangcilint g

diff --git a/.github/workflows/static-check.yml b/.github/workflows/static-check.yml
--- a/.github/workflows/static-check.yml
+++ b/.github/workflows/static-check.yml
@@ -33,7 +33,19 @@ jobs:
         uses: golangci/golangci-lint-action@v6
         with:
           version: latest
-          args: --timeout=20m --out-format=junit-xml --new-from-rev=HEAD~1 --issues-exit-code=0 | tee golangci.xml
+          args: --timeout=20m --issues-exit-code=0 --out-format=junit-xml | tee golangci.xml
           only-new-issues: true
       - if: always()
         uses: csexton/debugger-action@master
+      - name: analyze result
+        run: |
+          for errType in "error" "failure";do
+            num=$(egrep -c "[[:space:]]+<${errType} .*message=" golangci.xml)
+            echo "${errType} num is ${num}"
+            if [ "${errType}" == "error" ] && [ "${num}" != "0" ];then
+              echo "golangci-lint check failed"
+              exit 1
+            fi
+          done
+      
+          
